# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
            ],
        ),
    ]
